services:
  # React for CMS
  reactcms:
    image: node:20-alpine
    container_name: reactcms
    working_dir: /app
    volumes:
      - ./react-frontend:/app
    ports:
      - "5174:5173" # Different from main React app
    # command: sh -c "npm install && npm run dev"
    command: sh -c "npm install && npm start"