<?php

return [
    'categories' => [
        [
            'name' => 'Health & Wellness',
            'description' => 'Healthcare, fitness, and wellness services',
            'subcategories' => [
                ['name' => 'General Practice', 'description' => 'Family doctors and general practitioners'],
                ['name' => 'Dentistry', 'description' => 'Dental care and orthodontics'],
                ['name' => 'Physical Therapy', 'description' => 'Rehabilitation and physical therapy'],
                ['name' => 'Mental Health', 'description' => 'Counseling and therapy'],
                ['name' => 'Nutrition', 'description' => 'Dietitians and nutritionists'],
                ['name' => 'Fitness Centers', 'description' => 'Gyms and fitness clubs'],
                ['name' => 'Yoga & Pilates', 'description' => 'Yoga and pilates studios'],
                ['name' => 'Alternative Medicine', 'description' => 'Chiropractic, acupuncture, etc.'],
            ],
        ],
        [
            'name' => 'Education',
            'description' => 'Schools, tutoring, and educational services',
            'subcategories' => [
                ['name' => 'Primary Schools'],
                ['name' => 'Secondary Schools'],
                ['name' => 'Colleges & Universities'],
                ['name' => 'Tutoring Centers'],
                ['name' => 'Online Courses'],
                ['name' => 'Language Schools'],
                ['name' => 'Test Preparation'],
                ['name' => 'Music Schools'],
                ['name' => 'Art Schools'],
            ],
        ],
        [
            'name' => 'Home Services',
            'description' => 'Repairs, cleaning, and home improvement',
            'subcategories' => [
                ['name' => 'Plumbing'],
                ['name' => 'Electrical'],
                ['name' => 'Landscaping'],
                ['name' => 'Cleaning'],
                ['name' => 'Pest Control'],
                ['name' => 'Painting'],
                ['name' => 'HVAC'],
                ['name' => 'Roofing'],
                ['name' => 'Moving Services'],
                ['name' => 'Security Systems'],
            ],
        ],
        [
            'name' => 'Automotive',
            'description' => 'Car repair, detailing, and related services',
            'subcategories' => [
                ['name' => 'Auto Repair'],
                ['name' => 'Car Wash'],
                ['name' => 'Tire Services'],
                ['name' => 'Auto Detailing'],
                ['name' => 'Car Dealerships'],
                ['name' => 'Auto Glass'],
                ['name' => 'Oil Change'],
                ['name' => 'Towing'],
                ['name' => 'Car Rental'],
            ],
        ],
        [
            'name' => 'Beauty & Personal Care',
            'description' => 'Salons, spas, and personal grooming',
            'subcategories' => [
                ['name' => 'Hair Salons'],
                ['name' => 'Barbershops'],
                ['name' => 'Nail Salons'],
                ['name' => 'Spas'],
                ['name' => 'Massage'],
                ['name' => 'Makeup Artists'],
                ['name' => 'Skin Care'],
                ['name' => 'Tattoo & Piercing'],
            ],
        ],
        [
            'name' => 'Business Services',
            'description' => 'Consulting, marketing, and B2B services',
            'subcategories' => [
                ['name' => 'Consulting'],
                ['name' => 'Marketing'],
                ['name' => 'Accounting'],
                ['name' => 'Legal Services'],
                ['name' => 'IT Services'],
                ['name' => 'HR Services'],
                ['name' => 'Printing'],
                ['name' => 'Courier Services'],
                ['name' => 'Virtual Assistants'],
            ],
        ],
        [
            'name' => 'Legal',
            'description' => 'Lawyers, notaries, and legal advice',
            'subcategories' => [
                ['name' => 'Lawyers'],
                ['name' => 'Notaries'],
                ['name' => 'Legal Consulting'],
                ['name' => 'Mediation'],
                ['name' => 'Patent & IP Law'],
            ],
        ],
        [
            'name' => 'Financial',
            'description' => 'Accounting, tax, and financial planning',
            'subcategories' => [
                ['name' => 'Accountants'],
                ['name' => 'Tax Advisors'],
                ['name' => 'Financial Planners'],
                ['name' => 'Bookkeeping'],
                ['name' => 'Loan Services'],
                ['name' => 'Insurance'],
                ['name' => 'Investment Advisors'],
            ],
        ],
        [
            'name' => 'Technology',
            'description' => 'IT, software, and tech support',
            'subcategories' => [
                ['name' => 'IT Support'],
                ['name' => 'Software Development'],
                ['name' => 'Web Design'],
                ['name' => 'App Development'],
                ['name' => 'Cybersecurity'],
                ['name' => 'Cloud Services'],
                ['name' => 'Networking'],
                ['name' => 'Data Recovery'],
            ],
        ],
        [
            'name' => 'Events & Entertainment',
            'description' => 'Event planning, DJs, and entertainment',
            'subcategories' => [
                ['name' => 'Event Planners'],
                ['name' => 'DJs'],
                ['name' => 'Musicians'],
                ['name' => 'Catering'],
                ['name' => 'Photographers'],
                ['name' => 'Videographers'],
                ['name' => 'Party Rentals'],
                ['name' => 'Florists'],
                ['name' => 'MCs & Hosts'],
            ],
        ],
        [
            'name' => 'Pets & Animals',
            'description' => 'Veterinary, grooming, and pet care',
            'subcategories' => [
                ['name' => 'Veterinarians'],
                ['name' => 'Pet Grooming'],
                ['name' => 'Pet Boarding'],
                ['name' => 'Dog Walking'],
                ['name' => 'Pet Training'],
                ['name' => 'Pet Stores'],
            ],
        ],
        [
            'name' => 'Real Estate',
            'description' => 'Agents, property management, and rentals',
            'subcategories' => [
                ['name' => 'Real Estate Agents'],
                ['name' => 'Property Management'],
                ['name' => 'Rental Agencies'],
                ['name' => 'Appraisers'],
                ['name' => 'Home Inspectors'],
            ],
        ],
        [
            'name' => 'Food & Beverage',
            'description' => 'Catering, restaurants, and food delivery',
            'subcategories' => [
                ['name' => 'Restaurants'],
                ['name' => 'Cafes'],
                ['name' => 'Catering'],
                ['name' => 'Food Trucks'],
                ['name' => 'Bakeries'],
                ['name' => 'Bars & Pubs'],
                ['name' => 'Food Delivery'],
                ['name' => 'Grocery Stores'],
            ],
        ],
        [
            'name' => 'Travel & Transport',
            'description' => 'Travel agencies, taxis, and logistics',
            'subcategories' => [
                ['name' => 'Travel Agencies'],
                ['name' => 'Taxi Services'],
                ['name' => 'Car Rentals'],
                ['name' => 'Logistics'],
                ['name' => 'Bus Services'],
                ['name' => 'Airport Shuttles'],
                ['name' => 'Tour Operators'],
            ],
        ],
        [
            'name' => 'Sports & Recreation',
            'description' => 'Gyms, trainers, and sports clubs',
            'subcategories' => [
                ['name' => 'Gyms'],
                ['name' => 'Personal Trainers'],
                ['name' => 'Sports Clubs'],
                ['name' => 'Yoga Studios'],
                ['name' => 'Martial Arts'],
                ['name' => 'Dance Studios'],
                ['name' => 'Swimming Pools'],
            ],
        ],
        [
            'name' => 'Retail',
            'description' => 'Shops, e-commerce, and retail services',
            'subcategories' => [
                ['name' => 'Clothing Stores'],
                ['name' => 'Electronics Stores'],
                ['name' => 'Bookstores'],
                ['name' => 'Jewelry Stores'],
                ['name' => 'Toy Stores'],
                ['name' => 'Supermarkets'],
                ['name' => 'Online Shops'],
            ],
        ],
        [
            'name' => 'Construction',
            'description' => 'Builders, contractors, and construction services',
            'subcategories' => [
                ['name' => 'General Contractors'],
                ['name' => 'Architects'],
                ['name' => 'Engineers'],
                ['name' => 'Surveyors'],
                ['name' => 'Interior Designers'],
                ['name' => 'Demolition'],
            ],
        ],
        [
            'name' => 'Childcare',
            'description' => 'Daycare, babysitting, and child services',
            'subcategories' => [
                ['name' => 'Daycare Centers'],
                ['name' => 'Babysitters'],
                ['name' => 'Nannies'],
                ['name' => 'After School Programs'],
            ],
        ],
        [
            'name' => 'Elderly Care',
            'description' => 'Senior care and assisted living',
            'subcategories' => [
                ['name' => 'Assisted Living'],
                ['name' => 'Home Care'],
                ['name' => 'Nursing Homes'],
                ['name' => 'Hospice Care'],
            ],
        ],
        [
            'name' => 'Cleaning',
            'description' => 'Residential and commercial cleaning',
            'subcategories' => [
                ['name' => 'Home Cleaning'],
                ['name' => 'Office Cleaning'],
                ['name' => 'Window Cleaning'],
                ['name' => 'Carpet Cleaning'],
                ['name' => 'Pressure Washing'],
            ],
        ],
        [
            'name' => 'Other',
            'description' => 'Miscellaneous services',
            'subcategories' => [
                ['name' => 'Other'],
            ],
        ],
    ],
    'service_categories' => [
        ['name' => 'Plumbing', 'description' => 'Pipe repairs, installations, and maintenance'],
        ['name' => 'Electrical', 'description' => 'Wiring, lighting, and electrical repairs'],
        ['name' => 'Landscaping', 'description' => 'Gardening, lawn care, and landscaping'],
        ['name' => 'Tutoring', 'description' => 'Academic and skills tutoring'],
        ['name' => 'Fitness Training', 'description' => 'Personal trainers and fitness classes'],
        ['name' => 'Massage Therapy', 'description' => 'Massage and bodywork services'],
        ['name' => 'Hairdressing', 'description' => 'Haircuts, styling, and coloring'],
        ['name' => 'Makeup', 'description' => 'Makeup artists and beauty services'],
        ['name' => 'Photography', 'description' => 'Photographers and photo studios'],
        ['name' => 'Catering', 'description' => 'Food catering for events'],
        ['name' => 'DJ Services', 'description' => 'Music and DJ services for events'],
        ['name' => 'Pet Grooming', 'description' => 'Pet grooming and care'],
        ['name' => 'Car Wash', 'description' => 'Car washing and detailing'],
        ['name' => 'Legal Advice', 'description' => 'Legal consulting and advice'],
        ['name' => 'Tax Preparation', 'description' => 'Tax filing and preparation'],
        ['name' => 'Software Development', 'description' => 'Custom software and app development'],
        ['name' => 'IT Support', 'description' => 'Technical support and troubleshooting'],
        ['name' => 'Event Planning', 'description' => 'Event organization and planning'],
        ['name' => 'House Cleaning', 'description' => 'Home and apartment cleaning'],
        ['name' => 'Moving Services', 'description' => 'Moving and relocation services'],
        ['name' => 'Elderly Care', 'description' => 'In-home care for seniors'],
        ['name' => 'Childcare', 'description' => 'Babysitting and daycare'],
        ['name' => 'Translation', 'description' => 'Language translation services'],
        ['name' => 'Graphic Design', 'description' => 'Logos, branding, and design'],
        ['name' => 'Other', 'description' => 'Miscellaneous service categories'],
    ],
]; 